import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import {ReactNode, useContext} from "react";
import 'react-toastify/dist/ReactToastify.css';
import { actions, Store } from "../utils/Store";
import { Menu } from "@headlessui/react";
import { ToastContainer } from "react-toastify";


interface Props {
    children: ReactNode;
}

const Layout = ({children, ...props}: Props) => {

    const {status, data: session} = useSession();

    const {state, dispatch} = useContext(Store);
    const {cart} = state;

    const logoutHandler = () => {

        dispatch({type: actions.CART_REST});

        signOut({callbackUrl: '/login'});
    }

    return (
        <>
          <Head>
            <title>Amazona</title>
            <meta name="description" content="Generated by Ramy Mohamed" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <ToastContainer position="bottom-center" limit={1} />

          <div className="flex min-h-screen flex-col justify-between">
            <header>
                <nav className="flex h-12 items-center px-4 justify-between shadow-md">
                    <Link href="/">
                        <a className="text-lg font-bold">Amazona</a>
                    </Link>
                    <div>
                        <Link href="/cart">
                            <a className="p-2">
                                Cart 
                                {cart.cartItems.length > 0 && <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">{cart.cartItems.reduce((a: any, c: any)  => a + c.quantity, 0)}</span>}
                            </a>
                        </Link>
                        {
                            status === 'loading' ?
                            ('loading') :
                            session?.user ? (
                                //@ts-ignore
                                <Menu as="div" className="relative inline-block">
                                    <Menu.Button className="text-blue-600">
                                        {session.user?.name}
                                    </Menu.Button>
                                    <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white shadow-lg">
                                        <Menu.Item>
                                            <Link href="/profile">
                                                <a className="dropdown-link">
                                                    Profile
                                                </a>
                                            </Link>
                                        </Menu.Item>
                                        <Menu.Item>
                                            <Link href="/order-history">
                                                <a className="dropdown-link">
                                                    Order History
                                                </a>
                                            </Link>
                                        </Menu.Item>
                                        <Menu.Item>
                                                <a 
                                                className="dropdown-link"
                                                href="#"
                                                onClick={logoutHandler}
                                                >
                                                 Logout
                                                </a>
                                        </Menu.Item>
                                    </Menu.Items>
                                </Menu>
                            ) :
                            (<Link href="/login">
                             <a className="p-2">Login</a>
                            </Link>)
                        }
                    </div>
                </nav>
            </header>
            <main className="container m-auto mt-4 px-4">
                {children}
            </main>
            <footer className="flex h-10 justify-center items-center shadow-inner"><p>Copyright Amazona 2022</p></footer>
          </div>
        </>
    );
}

export default Layout;